### ISSUE TITLE
Warning: WebView has been extracted from react-native core and will be reemoed in a future release. It can now be installed and imported from 'react-native-webview' instead of 'react-native' 

### ISSUE THREAD

**Issue by rajeshmarotu** [xcarpentier/react-native-linkedin#126]
Description
Warning: WebView has been extracted from react-native core and will be reemoed in a future release. It can now be installed and imported from 'react-native-webview' instead of 'react-native'.

Expected Results
On clicking login using linked in button it should work fine without any error

Additional Information
"react": "16.8.3",
"react-native": "0.59.8",
"react-native-linkedin": "^1.3.2"

**Comment by vikaskhandekar001** [comment]
i am facing the same issue .did you find the solution?

**Comment by rajeshmarotu** [comment]
Hi @vikaskhandekar001  Now it's solved. Earlier the package was using WebView from react-native which has been extracted from react-native core. I think recent commit they have pushed (Separat package for WebView ) solves the issue.

**Comment by vidit-bhatia** [comment]
Can we have a release for this RN 0.60.4 has completely removed webview and my app is breaking we are looking to upgrade for some other reasons

**Comment by DmitriyNikolenko** [comment]
Temp solution

> const ReactNative = require('react-native');
> 
> Object.defineProperty(ReactNative, 'WebView', {
> 	get(): any {
> 		return require('react-native-webview').WebView;
> 	},
> });

**Comment by moamen-naanou** [comment]
I got it solved by following these steps:

1- When installing this package, I got a message says that WebView is not provided anymore by 'react-native' package and we should use 'react-native-webview' instead. but I checked the master branch and found that it is using the correct package, so for first step, use `yarn add https://github.com/xcarpentier/react-native-linkedin` instead of `yarn add react-native-linkedin`

2- Manual link is required for RNCWebView so we need to open the XCode project from <project_root_dir>/ios   then drag & drop **RNCWebView.xcodeproj** from node_modules/react-native-webview/ios   to **Libraries**

3- In XCode, open **Build Phases** -> **Link Binary With Libraries** then click on '+' button and type `libRNCWebView.a`.

4- Close XCode project and go to ios directory then run `pod install`.

Problem solved.

**Comment by godsehitesh** [comment]
My problem was solved by adding the following as props to LinkedInModal:

ref={ref => {this.modal = ref }}
permissions={['r_liteprofile', 'r_emailaddress']}

**Comment by tparesi** [comment]
Please publish your newest code to npm - as it has fixed this issue.

**Comment by xcarpentier** [comment]
fixed with `ˆ2.0.3`
