### ISSUE TITLE
on login or sign up, it redirects to redirect link page instead of giving token and login into app

### ISSUE THREAD

**Issue by Shoukat488** [xcarpentier/react-native-linkedin#178]

**Comment by mensonones** [comment]
could provide more details? printscreens, logs..

**Comment by AndreUskovv** [comment]
I get this problem too. 

**Current Behavior**

I'm trying to login via linkedIn account on the android emulator and this.onNavigationStateChange function redirects me to https://x.gloat.com/welcome/social-auth-error?auth_failed=social&reason=canceled. If I test application with Debug Remote JS I can login successfully. On the real android device I also cannot login via linkedIn. On the ios simulator all right works.

**Expected Behavior**

I can login successfully on both platforms

**How to reproduce**

- Open app
- Press on the LinkedIn button
- WebView is openning
- Enter credentials of linkedIn account
- WebView is changed, but doesn't close

**Your Environment**

"expo": "^40.0.0",
"react": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
"react-native-linkedin": "^2.1.1",
"react-native-webview": "11.0.0"

**Screenshots**

![Screenshot_1616571510](https://user-images.githubusercontent.com/50620068/112273110-a4e5e180-8c85-11eb-9657-1ee712a1f87e.png)
![Screenshot_1616571522](https://user-images.githubusercontent.com/50620068/112273195-be872900-8c85-11eb-9c89-d6cfcb3bd5a4.png)

**Comment by mensonones** [comment]
@AndreUskovv , follow the tutorial: https://dev.to/mensonones/login-com-linkedin-usando-react-native-288n

if you still can't, let me know

**Comment by AndreUskovv** [comment]
@mensonones I read the tutorial but my problem is actual yet.

My LinkedIn login component is
--------------------------------------------------------------
<img width="613" alt="Снимок экрана 2021-03-24 в 15 42 40" src="https://user-images.githubusercontent.com/50620068/112320339-9dd7c700-8cb7-11eb-9387-06bb02c6c327.png">

Video:
---------------------------------------------------------------

1) before Debug Remote JS

https://user-images.githubusercontent.com/50620068/112320635-dd061800-8cb7-11eb-8be9-b3e41f35abb7.mov

2) after Debug Remote JS


https://user-images.githubusercontent.com/50620068/112320726-f4450580-8cb7-11eb-8911-8b049ed3335b.mov

**Comment by mensonones** [comment]
yours redirectUri is the same as the one you set up on linkedin?

**Comment by AndreUskovv** [comment]
yes. Otherwise I couldn't login on the second video

**Comment by mensonones** [comment]
send me the link to your repository that I will test locally. after my work i will test

**Comment by AndreUskovv** [comment]
This project is commercial, so I will create new project with linkedIn functionality and send you the link

**Comment by mensonones** [comment]
ok, @AndreUskovv

**Comment by AndreUskovv** [comment]
@mensonones could you say your email to add in bitbucket?

**Comment by mensonones** [comment]
> @mensonones could you say your email to add in bitbucket?

mensones.1@gmail.com

**Comment by AndreUskovv** [comment]
> mensones.1@gmail.com

send you invitation :)

**Comment by mensonones** [comment]
accepted invite, but error: The owner of this repository (AndrewUskov) is already at their plan limit and will need to upgrade before adding more users.

**Comment by AndreUskovv** [comment]
ok. resent invitation

**Comment by AndreUskovv** [comment]
@mensonones Hi, Emerson! Did you test app? )

**Comment by mensonones** [comment]
Hey, @AndreUskovv! I tested it and the problem must be with your redirect link. I tested it with your code and in debug I didn't get a response from the token. I used my keys and put a redirection url and it worked both in debug and in release.

**Comment by AndreUskovv** [comment]
@mensonones understood. If it's possible, could you push code with your keys? Thank you very much for the helping!

**Comment by mensonones** [comment]
I deleted my app in dev linkedin, @AndreUskovv :/

**Comment by adorum** [comment]
HI @AndreUskovv . I have a same issue. Have you found out, why it does not work on android emulator without remote js debug?
